apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.appName}}
  type: {{.Values.serviceType}}  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80